/* Generated by Yosys 0.8+     369 (git sha1 ea0e0722, clang 10.0.1 -fPIC -Os) */

(* \nmigen.hierarchy  = "top.pixel1" *)
(* generator = "nMigen" *)
module pixel1(val_in, rst, clk, ssss, val_out, valid);
  wire \$1 ;
  wire [18:0] \$100 ;
  wire [18:0] \$102 ;
  wire [17:0] \$103 ;
  wire [18:0] \$105 ;
  wire [18:0] \$107 ;
  wire [17:0] \$108 ;
  wire \$11 ;
  wire [18:0] \$110 ;
  wire [18:0] \$112 ;
  wire [17:0] \$113 ;
  wire [18:0] \$115 ;
  wire [18:0] \$117 ;
  wire [17:0] \$118 ;
  wire [18:0] \$120 ;
  wire [18:0] \$122 ;
  wire [17:0] \$123 ;
  wire [18:0] \$125 ;
  wire [18:0] \$127 ;
  wire [17:0] \$128 ;
  wire \$13 ;
  wire [18:0] \$130 ;
  wire [18:0] \$132 ;
  wire [17:0] \$133 ;
  wire [18:0] \$135 ;
  wire [18:0] \$137 ;
  wire [17:0] \$138 ;
  wire [18:0] \$140 ;
  wire [18:0] \$142 ;
  wire [17:0] \$143 ;
  wire [18:0] \$145 ;
  wire \$15 ;
  wire \$17 ;
  wire \$19 ;
  wire \$21 ;
  wire \$23 ;
  wire \$25 ;
  wire \$27 ;
  wire \$29 ;
  wire \$3 ;
  wire \$31 ;
  wire \$33 ;
  wire \$35 ;
  wire \$37 ;
  wire \$39 ;
  wire \$41 ;
  wire \$43 ;
  wire \$45 ;
  wire \$47 ;
  wire \$49 ;
  wire \$5 ;
  wire \$51 ;
  wire \$53 ;
  wire \$55 ;
  wire \$57 ;
  wire \$59 ;
  wire \$61 ;
  wire \$63 ;
  wire \$65 ;
  wire \$67 ;
  wire [17:0] \$69 ;
  wire \$7 ;
  wire [17:0] \$70 ;
  wire [18:0] \$72 ;
  wire [17:0] \$73 ;
  wire [18:0] \$75 ;
  wire [18:0] \$77 ;
  wire [17:0] \$78 ;
  wire [18:0] \$80 ;
  wire [18:0] \$82 ;
  wire [17:0] \$83 ;
  wire [18:0] \$85 ;
  wire [18:0] \$87 ;
  wire [17:0] \$88 ;
  wire \$9 ;
  wire [18:0] \$90 ;
  wire [18:0] \$92 ;
  wire [17:0] \$93 ;
  wire [18:0] \$95 ;
  wire [18:0] \$97 ;
  wire [17:0] \$98 ;
  (* src = "./migen_src/normalize.py:13" *)
  reg [4:0] \$next\ssss ;
  (* src = "./migen_src/normalize.py:12" *)
  reg [15:0] \$next\val_out ;
  (* src = "/anaconda3/envs/py36/lib/python3.6/site-packages/nmigen/hdl/ir.py:329" *)
  input clk;
  (* src = "/anaconda3/envs/py36/lib/python3.6/site-packages/nmigen/hdl/ir.py:329" *)
  input rst;
  (* init = 5'h00 *)
  (* src = "./migen_src/normalize.py:13" *)
  output [4:0] ssss;
  reg [4:0] ssss = 5'h00;
  (* src = "./migen_src/normalize.py:11" *)
  input [16:0] val_in;
  (* init = 16'h0000 *)
  (* src = "./migen_src/normalize.py:12" *)
  output [15:0] val_out;
  reg [15:0] val_out = 16'h0000;
  (* src = "./migen_src/normalize.py:14" *)
  input valid;
  assign \$9  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff1;
  assign \$100  = \$98  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$103  = val_in + (* src = "./migen_src/normalize.py:40" *) 9'h100;
  assign \$105  = \$103  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$108  = val_in + (* src = "./migen_src/normalize.py:40" *) 10'h200;
  assign \$110  = \$108  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$113  = val_in + (* src = "./migen_src/normalize.py:40" *) 11'h400;
  assign \$115  = \$113  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$118  = val_in + (* src = "./migen_src/normalize.py:40" *) 12'h800;
  assign \$11  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffe1;
  assign \$120  = \$118  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$123  = val_in + (* src = "./migen_src/normalize.py:40" *) 13'h1000;
  assign \$125  = \$123  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$128  = val_in + (* src = "./migen_src/normalize.py:40" *) 14'h2000;
  assign \$130  = \$128  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$133  = val_in + (* src = "./migen_src/normalize.py:40" *) 15'h4000;
  assign \$135  = \$133  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$138  = val_in + (* src = "./migen_src/normalize.py:40" *) 16'h8000;
  assign \$13  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffc1;
  assign \$140  = \$138  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$143  = val_in + (* src = "./migen_src/normalize.py:40" *) 17'h10000;
  assign \$145  = \$143  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$15  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff81;
  assign \$17  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff01;
  assign \$1  = val_in[16] == (* src = "./migen_src/normalize.py:26" *) 1'h1;
  assign \$19  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fe01;
  assign \$21  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fc01;
  assign \$23  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f801;
  assign \$25  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f001;
  assign \$27  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1e001;
  assign \$29  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1c001;
  assign \$31  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h18001;
  assign \$33  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h10001;
  assign \$35  = val_in[16] == (* src = "./migen_src/normalize.py:26" *) 1'h1;
  assign \$37  = val_in == (* src = "./migen_src/normalize.py:29" *) 17'h1ffff;
  assign \$3  = val_in == (* src = "./migen_src/normalize.py:29" *) 17'h1ffff;
  assign \$39  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fffd;
  assign \$41  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff9;
  assign \$43  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff1;
  assign \$45  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffe1;
  assign \$47  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffc1;
  assign \$49  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff81;
  assign \$51  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff01;
  assign \$53  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fe01;
  assign \$55  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fc01;
  assign \$57  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f801;
  assign \$5  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fffd;
  assign \$59  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f001;
  assign \$61  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1e001;
  assign \$63  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1c001;
  assign \$65  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h18001;
  assign \$67  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h10001;
  assign \$70  = val_in + (* src = "./migen_src/normalize.py:32" *) 1'h1;
  assign \$73  = val_in + (* src = "./migen_src/normalize.py:40" *) 3'h4;
  assign \$75  = \$73  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$78  = val_in + (* src = "./migen_src/normalize.py:40" *) 4'h8;
  assign \$7  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff9;
  assign \$80  = \$78  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$83  = val_in + (* src = "./migen_src/normalize.py:40" *) 5'h10;
  assign \$85  = \$83  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$88  = val_in + (* src = "./migen_src/normalize.py:40" *) 6'h20;
  assign \$90  = \$88  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$93  = val_in + (* src = "./migen_src/normalize.py:40" *) 7'h40;
  assign \$95  = \$93  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$98  = val_in + (* src = "./migen_src/normalize.py:40" *) 8'h80;
  always @(posedge clk)
      val_out <= \$next\val_out ;
  always @(posedge clk)
      ssss <= \$next\ssss ;
  always @* begin
    \$next\ssss  = ssss;
    casez (valid)
      1'h1:
          casez (\$1 )
            1'h1:
                casez ({ \$33 , \$31 , \$29 , \$27 , \$25 , \$23 , \$21 , \$19 , \$17 , \$15 , \$13 , \$11 , \$9 , \$7 , \$5 , \$3  })
                  16'bzzzzzzzzzzzzzzz1:
                      \$next\ssss  = 5'h01;
                  16'bzzzzzzzzzzzzzz1z:
                      \$next\ssss  = 5'h02;
                  16'bzzzzzzzzzzzzz1zz:
                      \$next\ssss  = 5'h03;
                  16'bzzzzzzzzzzzz1zzz:
                      \$next\ssss  = 5'h04;
                  16'bzzzzzzzzzzz1zzzz:
                      \$next\ssss  = 5'h05;
                  16'bzzzzzzzzzz1zzzzz:
                      \$next\ssss  = 5'h06;
                  16'bzzzzzzzzz1zzzzzz:
                      \$next\ssss  = 5'h07;
                  16'bzzzzzzzz1zzzzzzz:
                      \$next\ssss  = 5'h08;
                  16'bzzzzzzz1zzzzzzzz:
                      \$next\ssss  = 5'h09;
                  16'bzzzzzz1zzzzzzzzz:
                      \$next\ssss  = 5'h0a;
                  16'bzzzzz1zzzzzzzzzz:
                      \$next\ssss  = 5'h0b;
                  16'bzzzz1zzzzzzzzzzz:
                      \$next\ssss  = 5'h0c;
                  16'bzzz1zzzzzzzzzzzz:
                      \$next\ssss  = 5'h0d;
                  16'bzz1zzzzzzzzzzzzz:
                      \$next\ssss  = 5'h0e;
                  16'bz1zzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h0f;
                  16'b1zzzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h10;
                endcase
            1'hz:
                casez ({ val_in[0], val_in[1], val_in[2], val_in[3], val_in[4], val_in[5], val_in[6], val_in[7], val_in[8], val_in[9], val_in[10], val_in[11], val_in[12], val_in[13], val_in[14], val_in[15] })
                  16'bzzzzzzzzzzzzzzz1:
                      \$next\ssss  = 5'h10;
                  16'bzzzzzzzzzzzzzz1z:
                      \$next\ssss  = 5'h0f;
                  16'bzzzzzzzzzzzzz1zz:
                      \$next\ssss  = 5'h0e;
                  16'bzzzzzzzzzzzz1zzz:
                      \$next\ssss  = 5'h0d;
                  16'bzzzzzzzzzzz1zzzz:
                      \$next\ssss  = 5'h0c;
                  16'bzzzzzzzzzz1zzzzz:
                      \$next\ssss  = 5'h0b;
                  16'bzzzzzzzzz1zzzzzz:
                      \$next\ssss  = 5'h0a;
                  16'bzzzzzzzz1zzzzzzz:
                      \$next\ssss  = 5'h09;
                  16'bzzzzzzz1zzzzzzzz:
                      \$next\ssss  = 5'h08;
                  16'bzzzzzz1zzzzzzzzz:
                      \$next\ssss  = 5'h07;
                  16'bzzzzz1zzzzzzzzzz:
                      \$next\ssss  = 5'h06;
                  16'bzzzz1zzzzzzzzzzz:
                      \$next\ssss  = 5'h05;
                  16'bzzz1zzzzzzzzzzzz:
                      \$next\ssss  = 5'h04;
                  16'bzz1zzzzzzzzzzzzz:
                      \$next\ssss  = 5'h03;
                  16'bz1zzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h02;
                  16'b1zzzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h01;
                  16'hzzzz:
                      \$next\ssss  = 5'h00;
                endcase
          endcase
    endcase
    casez (rst)
      1'h1:
          \$next\ssss  = 5'h00;
    endcase
  end
  always @* begin
    \$next\val_out  = val_out;
    casez (valid)
      1'h1:
          casez (\$35 )
            1'h1:
                casez ({ \$67 , \$65 , \$63 , \$61 , \$59 , \$57 , \$55 , \$53 , \$51 , \$49 , \$47 , \$45 , \$43 , \$41 , \$39 , \$37  })
                  16'bzzzzzzzzzzzzzzz1:
                      \$next\val_out  = \$69 [15:0];
                  16'bzzzzzzzzzzzzzz1z:
                      \$next\val_out  = \$72 [15:0];
                  16'bzzzzzzzzzzzzz1zz:
                      \$next\val_out  = \$77 [15:0];
                  16'bzzzzzzzzzzzz1zzz:
                      \$next\val_out  = \$82 [15:0];
                  16'bzzzzzzzzzzz1zzzz:
                      \$next\val_out  = \$87 [15:0];
                  16'bzzzzzzzzzz1zzzzz:
                      \$next\val_out  = \$92 [15:0];
                  16'bzzzzzzzzz1zzzzzz:
                      \$next\val_out  = \$97 [15:0];
                  16'bzzzzzzzz1zzzzzzz:
                      \$next\val_out  = \$102 [15:0];
                  16'bzzzzzzz1zzzzzzzz:
                      \$next\val_out  = \$107 [15:0];
                  16'bzzzzzz1zzzzzzzzz:
                      \$next\val_out  = \$112 [15:0];
                  16'bzzzzz1zzzzzzzzzz:
                      \$next\val_out  = \$117 [15:0];
                  16'bzzzz1zzzzzzzzzzz:
                      \$next\val_out  = \$122 [15:0];
                  16'bzzz1zzzzzzzzzzzz:
                      \$next\val_out  = \$127 [15:0];
                  16'bzz1zzzzzzzzzzzzz:
                      \$next\val_out  = \$132 [15:0];
                  16'bz1zzzzzzzzzzzzzz:
                      \$next\val_out  = \$137 [15:0];
                  16'b1zzzzzzzzzzzzzzz:
                      \$next\val_out  = \$142 [15:0];
                endcase
            1'hz:
                \$next\val_out  = val_in[15:0];
          endcase
    endcase
    casez (rst)
      1'h1:
          \$next\val_out  = 16'h0000;
    endcase
  end
  assign \$69  = \$70 ;
  assign \$72  = \$75 ;
  assign \$77  = \$80 ;
  assign \$82  = \$85 ;
  assign \$87  = \$90 ;
  assign \$92  = \$95 ;
  assign \$97  = \$100 ;
  assign \$102  = \$105 ;
  assign \$107  = \$110 ;
  assign \$112  = \$115 ;
  assign \$117  = \$120 ;
  assign \$122  = \$125 ;
  assign \$127  = \$130 ;
  assign \$132  = \$135 ;
  assign \$137  = \$140 ;
  assign \$142  = \$145 ;
endmodule

(* \nmigen.hierarchy  = "top.pixel2" *)
(* generator = "nMigen" *)
module pixel2(val_in, rst, clk, ssss, val_out, valid);
  wire \$1 ;
  wire [18:0] \$100 ;
  wire [18:0] \$102 ;
  wire [17:0] \$103 ;
  wire [18:0] \$105 ;
  wire [18:0] \$107 ;
  wire [17:0] \$108 ;
  wire \$11 ;
  wire [18:0] \$110 ;
  wire [18:0] \$112 ;
  wire [17:0] \$113 ;
  wire [18:0] \$115 ;
  wire [18:0] \$117 ;
  wire [17:0] \$118 ;
  wire [18:0] \$120 ;
  wire [18:0] \$122 ;
  wire [17:0] \$123 ;
  wire [18:0] \$125 ;
  wire [18:0] \$127 ;
  wire [17:0] \$128 ;
  wire \$13 ;
  wire [18:0] \$130 ;
  wire [18:0] \$132 ;
  wire [17:0] \$133 ;
  wire [18:0] \$135 ;
  wire [18:0] \$137 ;
  wire [17:0] \$138 ;
  wire [18:0] \$140 ;
  wire [18:0] \$142 ;
  wire [17:0] \$143 ;
  wire [18:0] \$145 ;
  wire \$15 ;
  wire \$17 ;
  wire \$19 ;
  wire \$21 ;
  wire \$23 ;
  wire \$25 ;
  wire \$27 ;
  wire \$29 ;
  wire \$3 ;
  wire \$31 ;
  wire \$33 ;
  wire \$35 ;
  wire \$37 ;
  wire \$39 ;
  wire \$41 ;
  wire \$43 ;
  wire \$45 ;
  wire \$47 ;
  wire \$49 ;
  wire \$5 ;
  wire \$51 ;
  wire \$53 ;
  wire \$55 ;
  wire \$57 ;
  wire \$59 ;
  wire \$61 ;
  wire \$63 ;
  wire \$65 ;
  wire \$67 ;
  wire [17:0] \$69 ;
  wire \$7 ;
  wire [17:0] \$70 ;
  wire [18:0] \$72 ;
  wire [17:0] \$73 ;
  wire [18:0] \$75 ;
  wire [18:0] \$77 ;
  wire [17:0] \$78 ;
  wire [18:0] \$80 ;
  wire [18:0] \$82 ;
  wire [17:0] \$83 ;
  wire [18:0] \$85 ;
  wire [18:0] \$87 ;
  wire [17:0] \$88 ;
  wire \$9 ;
  wire [18:0] \$90 ;
  wire [18:0] \$92 ;
  wire [17:0] \$93 ;
  wire [18:0] \$95 ;
  wire [18:0] \$97 ;
  wire [17:0] \$98 ;
  (* src = "./migen_src/normalize.py:13" *)
  reg [4:0] \$next\ssss ;
  (* src = "./migen_src/normalize.py:12" *)
  reg [15:0] \$next\val_out ;
  (* src = "/anaconda3/envs/py36/lib/python3.6/site-packages/nmigen/hdl/ir.py:329" *)
  input clk;
  (* src = "/anaconda3/envs/py36/lib/python3.6/site-packages/nmigen/hdl/ir.py:329" *)
  input rst;
  (* init = 5'h00 *)
  (* src = "./migen_src/normalize.py:13" *)
  output [4:0] ssss;
  reg [4:0] ssss = 5'h00;
  (* src = "./migen_src/normalize.py:11" *)
  input [16:0] val_in;
  (* init = 16'h0000 *)
  (* src = "./migen_src/normalize.py:12" *)
  output [15:0] val_out;
  reg [15:0] val_out = 16'h0000;
  (* src = "./migen_src/normalize.py:14" *)
  input valid;
  assign \$9  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff1;
  assign \$100  = \$98  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$103  = val_in + (* src = "./migen_src/normalize.py:40" *) 9'h100;
  assign \$105  = \$103  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$108  = val_in + (* src = "./migen_src/normalize.py:40" *) 10'h200;
  assign \$110  = \$108  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$113  = val_in + (* src = "./migen_src/normalize.py:40" *) 11'h400;
  assign \$115  = \$113  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$118  = val_in + (* src = "./migen_src/normalize.py:40" *) 12'h800;
  assign \$11  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffe1;
  assign \$120  = \$118  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$123  = val_in + (* src = "./migen_src/normalize.py:40" *) 13'h1000;
  assign \$125  = \$123  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$128  = val_in + (* src = "./migen_src/normalize.py:40" *) 14'h2000;
  assign \$130  = \$128  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$133  = val_in + (* src = "./migen_src/normalize.py:40" *) 15'h4000;
  assign \$135  = \$133  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$138  = val_in + (* src = "./migen_src/normalize.py:40" *) 16'h8000;
  assign \$13  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffc1;
  assign \$140  = \$138  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$143  = val_in + (* src = "./migen_src/normalize.py:40" *) 17'h10000;
  assign \$145  = \$143  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$15  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff81;
  assign \$17  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff01;
  assign \$1  = val_in[16] == (* src = "./migen_src/normalize.py:26" *) 1'h1;
  assign \$19  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fe01;
  assign \$21  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fc01;
  assign \$23  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f801;
  assign \$25  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f001;
  assign \$27  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1e001;
  assign \$29  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1c001;
  assign \$31  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h18001;
  assign \$33  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h10001;
  assign \$35  = val_in[16] == (* src = "./migen_src/normalize.py:26" *) 1'h1;
  assign \$37  = val_in == (* src = "./migen_src/normalize.py:29" *) 17'h1ffff;
  assign \$3  = val_in == (* src = "./migen_src/normalize.py:29" *) 17'h1ffff;
  assign \$39  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fffd;
  assign \$41  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff9;
  assign \$43  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff1;
  assign \$45  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffe1;
  assign \$47  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffc1;
  assign \$49  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff81;
  assign \$51  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff01;
  assign \$53  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fe01;
  assign \$55  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fc01;
  assign \$57  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f801;
  assign \$5  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fffd;
  assign \$59  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f001;
  assign \$61  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1e001;
  assign \$63  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1c001;
  assign \$65  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h18001;
  assign \$67  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h10001;
  assign \$70  = val_in + (* src = "./migen_src/normalize.py:32" *) 1'h1;
  assign \$73  = val_in + (* src = "./migen_src/normalize.py:40" *) 3'h4;
  assign \$75  = \$73  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$78  = val_in + (* src = "./migen_src/normalize.py:40" *) 4'h8;
  assign \$7  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff9;
  assign \$80  = \$78  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$83  = val_in + (* src = "./migen_src/normalize.py:40" *) 5'h10;
  assign \$85  = \$83  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$88  = val_in + (* src = "./migen_src/normalize.py:40" *) 6'h20;
  assign \$90  = \$88  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$93  = val_in + (* src = "./migen_src/normalize.py:40" *) 7'h40;
  assign \$95  = \$93  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$98  = val_in + (* src = "./migen_src/normalize.py:40" *) 8'h80;
  always @(posedge clk)
      val_out <= \$next\val_out ;
  always @(posedge clk)
      ssss <= \$next\ssss ;
  always @* begin
    \$next\ssss  = ssss;
    casez (valid)
      1'h1:
          casez (\$1 )
            1'h1:
                casez ({ \$33 , \$31 , \$29 , \$27 , \$25 , \$23 , \$21 , \$19 , \$17 , \$15 , \$13 , \$11 , \$9 , \$7 , \$5 , \$3  })
                  16'bzzzzzzzzzzzzzzz1:
                      \$next\ssss  = 5'h01;
                  16'bzzzzzzzzzzzzzz1z:
                      \$next\ssss  = 5'h02;
                  16'bzzzzzzzzzzzzz1zz:
                      \$next\ssss  = 5'h03;
                  16'bzzzzzzzzzzzz1zzz:
                      \$next\ssss  = 5'h04;
                  16'bzzzzzzzzzzz1zzzz:
                      \$next\ssss  = 5'h05;
                  16'bzzzzzzzzzz1zzzzz:
                      \$next\ssss  = 5'h06;
                  16'bzzzzzzzzz1zzzzzz:
                      \$next\ssss  = 5'h07;
                  16'bzzzzzzzz1zzzzzzz:
                      \$next\ssss  = 5'h08;
                  16'bzzzzzzz1zzzzzzzz:
                      \$next\ssss  = 5'h09;
                  16'bzzzzzz1zzzzzzzzz:
                      \$next\ssss  = 5'h0a;
                  16'bzzzzz1zzzzzzzzzz:
                      \$next\ssss  = 5'h0b;
                  16'bzzzz1zzzzzzzzzzz:
                      \$next\ssss  = 5'h0c;
                  16'bzzz1zzzzzzzzzzzz:
                      \$next\ssss  = 5'h0d;
                  16'bzz1zzzzzzzzzzzzz:
                      \$next\ssss  = 5'h0e;
                  16'bz1zzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h0f;
                  16'b1zzzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h10;
                endcase
            1'hz:
                casez ({ val_in[0], val_in[1], val_in[2], val_in[3], val_in[4], val_in[5], val_in[6], val_in[7], val_in[8], val_in[9], val_in[10], val_in[11], val_in[12], val_in[13], val_in[14], val_in[15] })
                  16'bzzzzzzzzzzzzzzz1:
                      \$next\ssss  = 5'h10;
                  16'bzzzzzzzzzzzzzz1z:
                      \$next\ssss  = 5'h0f;
                  16'bzzzzzzzzzzzzz1zz:
                      \$next\ssss  = 5'h0e;
                  16'bzzzzzzzzzzzz1zzz:
                      \$next\ssss  = 5'h0d;
                  16'bzzzzzzzzzzz1zzzz:
                      \$next\ssss  = 5'h0c;
                  16'bzzzzzzzzzz1zzzzz:
                      \$next\ssss  = 5'h0b;
                  16'bzzzzzzzzz1zzzzzz:
                      \$next\ssss  = 5'h0a;
                  16'bzzzzzzzz1zzzzzzz:
                      \$next\ssss  = 5'h09;
                  16'bzzzzzzz1zzzzzzzz:
                      \$next\ssss  = 5'h08;
                  16'bzzzzzz1zzzzzzzzz:
                      \$next\ssss  = 5'h07;
                  16'bzzzzz1zzzzzzzzzz:
                      \$next\ssss  = 5'h06;
                  16'bzzzz1zzzzzzzzzzz:
                      \$next\ssss  = 5'h05;
                  16'bzzz1zzzzzzzzzzzz:
                      \$next\ssss  = 5'h04;
                  16'bzz1zzzzzzzzzzzzz:
                      \$next\ssss  = 5'h03;
                  16'bz1zzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h02;
                  16'b1zzzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h01;
                  16'hzzzz:
                      \$next\ssss  = 5'h00;
                endcase
          endcase
    endcase
    casez (rst)
      1'h1:
          \$next\ssss  = 5'h00;
    endcase
  end
  always @* begin
    \$next\val_out  = val_out;
    casez (valid)
      1'h1:
          casez (\$35 )
            1'h1:
                casez ({ \$67 , \$65 , \$63 , \$61 , \$59 , \$57 , \$55 , \$53 , \$51 , \$49 , \$47 , \$45 , \$43 , \$41 , \$39 , \$37  })
                  16'bzzzzzzzzzzzzzzz1:
                      \$next\val_out  = \$69 [15:0];
                  16'bzzzzzzzzzzzzzz1z:
                      \$next\val_out  = \$72 [15:0];
                  16'bzzzzzzzzzzzzz1zz:
                      \$next\val_out  = \$77 [15:0];
                  16'bzzzzzzzzzzzz1zzz:
                      \$next\val_out  = \$82 [15:0];
                  16'bzzzzzzzzzzz1zzzz:
                      \$next\val_out  = \$87 [15:0];
                  16'bzzzzzzzzzz1zzzzz:
                      \$next\val_out  = \$92 [15:0];
                  16'bzzzzzzzzz1zzzzzz:
                      \$next\val_out  = \$97 [15:0];
                  16'bzzzzzzzz1zzzzzzz:
                      \$next\val_out  = \$102 [15:0];
                  16'bzzzzzzz1zzzzzzzz:
                      \$next\val_out  = \$107 [15:0];
                  16'bzzzzzz1zzzzzzzzz:
                      \$next\val_out  = \$112 [15:0];
                  16'bzzzzz1zzzzzzzzzz:
                      \$next\val_out  = \$117 [15:0];
                  16'bzzzz1zzzzzzzzzzz:
                      \$next\val_out  = \$122 [15:0];
                  16'bzzz1zzzzzzzzzzzz:
                      \$next\val_out  = \$127 [15:0];
                  16'bzz1zzzzzzzzzzzzz:
                      \$next\val_out  = \$132 [15:0];
                  16'bz1zzzzzzzzzzzzzz:
                      \$next\val_out  = \$137 [15:0];
                  16'b1zzzzzzzzzzzzzzz:
                      \$next\val_out  = \$142 [15:0];
                endcase
            1'hz:
                \$next\val_out  = val_in[15:0];
          endcase
    endcase
    casez (rst)
      1'h1:
          \$next\val_out  = 16'h0000;
    endcase
  end
  assign \$69  = \$70 ;
  assign \$72  = \$75 ;
  assign \$77  = \$80 ;
  assign \$82  = \$85 ;
  assign \$87  = \$90 ;
  assign \$92  = \$95 ;
  assign \$97  = \$100 ;
  assign \$102  = \$105 ;
  assign \$107  = \$110 ;
  assign \$112  = \$115 ;
  assign \$117  = \$120 ;
  assign \$122  = \$125 ;
  assign \$127  = \$130 ;
  assign \$132  = \$135 ;
  assign \$137  = \$140 ;
  assign \$142  = \$145 ;
endmodule

(* \nmigen.hierarchy  = "top.pixel3" *)
(* generator = "nMigen" *)
module pixel3(val_in, rst, clk, ssss, val_out, valid);
  wire \$1 ;
  wire [18:0] \$100 ;
  wire [18:0] \$102 ;
  wire [17:0] \$103 ;
  wire [18:0] \$105 ;
  wire [18:0] \$107 ;
  wire [17:0] \$108 ;
  wire \$11 ;
  wire [18:0] \$110 ;
  wire [18:0] \$112 ;
  wire [17:0] \$113 ;
  wire [18:0] \$115 ;
  wire [18:0] \$117 ;
  wire [17:0] \$118 ;
  wire [18:0] \$120 ;
  wire [18:0] \$122 ;
  wire [17:0] \$123 ;
  wire [18:0] \$125 ;
  wire [18:0] \$127 ;
  wire [17:0] \$128 ;
  wire \$13 ;
  wire [18:0] \$130 ;
  wire [18:0] \$132 ;
  wire [17:0] \$133 ;
  wire [18:0] \$135 ;
  wire [18:0] \$137 ;
  wire [17:0] \$138 ;
  wire [18:0] \$140 ;
  wire [18:0] \$142 ;
  wire [17:0] \$143 ;
  wire [18:0] \$145 ;
  wire \$15 ;
  wire \$17 ;
  wire \$19 ;
  wire \$21 ;
  wire \$23 ;
  wire \$25 ;
  wire \$27 ;
  wire \$29 ;
  wire \$3 ;
  wire \$31 ;
  wire \$33 ;
  wire \$35 ;
  wire \$37 ;
  wire \$39 ;
  wire \$41 ;
  wire \$43 ;
  wire \$45 ;
  wire \$47 ;
  wire \$49 ;
  wire \$5 ;
  wire \$51 ;
  wire \$53 ;
  wire \$55 ;
  wire \$57 ;
  wire \$59 ;
  wire \$61 ;
  wire \$63 ;
  wire \$65 ;
  wire \$67 ;
  wire [17:0] \$69 ;
  wire \$7 ;
  wire [17:0] \$70 ;
  wire [18:0] \$72 ;
  wire [17:0] \$73 ;
  wire [18:0] \$75 ;
  wire [18:0] \$77 ;
  wire [17:0] \$78 ;
  wire [18:0] \$80 ;
  wire [18:0] \$82 ;
  wire [17:0] \$83 ;
  wire [18:0] \$85 ;
  wire [18:0] \$87 ;
  wire [17:0] \$88 ;
  wire \$9 ;
  wire [18:0] \$90 ;
  wire [18:0] \$92 ;
  wire [17:0] \$93 ;
  wire [18:0] \$95 ;
  wire [18:0] \$97 ;
  wire [17:0] \$98 ;
  (* src = "./migen_src/normalize.py:13" *)
  reg [4:0] \$next\ssss ;
  (* src = "./migen_src/normalize.py:12" *)
  reg [15:0] \$next\val_out ;
  (* src = "/anaconda3/envs/py36/lib/python3.6/site-packages/nmigen/hdl/ir.py:329" *)
  input clk;
  (* src = "/anaconda3/envs/py36/lib/python3.6/site-packages/nmigen/hdl/ir.py:329" *)
  input rst;
  (* init = 5'h00 *)
  (* src = "./migen_src/normalize.py:13" *)
  output [4:0] ssss;
  reg [4:0] ssss = 5'h00;
  (* src = "./migen_src/normalize.py:11" *)
  input [16:0] val_in;
  (* init = 16'h0000 *)
  (* src = "./migen_src/normalize.py:12" *)
  output [15:0] val_out;
  reg [15:0] val_out = 16'h0000;
  (* src = "./migen_src/normalize.py:14" *)
  input valid;
  assign \$9  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff1;
  assign \$100  = \$98  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$103  = val_in + (* src = "./migen_src/normalize.py:40" *) 9'h100;
  assign \$105  = \$103  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$108  = val_in + (* src = "./migen_src/normalize.py:40" *) 10'h200;
  assign \$110  = \$108  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$113  = val_in + (* src = "./migen_src/normalize.py:40" *) 11'h400;
  assign \$115  = \$113  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$118  = val_in + (* src = "./migen_src/normalize.py:40" *) 12'h800;
  assign \$11  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffe1;
  assign \$120  = \$118  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$123  = val_in + (* src = "./migen_src/normalize.py:40" *) 13'h1000;
  assign \$125  = \$123  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$128  = val_in + (* src = "./migen_src/normalize.py:40" *) 14'h2000;
  assign \$130  = \$128  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$133  = val_in + (* src = "./migen_src/normalize.py:40" *) 15'h4000;
  assign \$135  = \$133  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$138  = val_in + (* src = "./migen_src/normalize.py:40" *) 16'h8000;
  assign \$13  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffc1;
  assign \$140  = \$138  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$143  = val_in + (* src = "./migen_src/normalize.py:40" *) 17'h10000;
  assign \$145  = \$143  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$15  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff81;
  assign \$17  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff01;
  assign \$1  = val_in[16] == (* src = "./migen_src/normalize.py:26" *) 1'h1;
  assign \$19  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fe01;
  assign \$21  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fc01;
  assign \$23  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f801;
  assign \$25  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f001;
  assign \$27  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1e001;
  assign \$29  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1c001;
  assign \$31  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h18001;
  assign \$33  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h10001;
  assign \$35  = val_in[16] == (* src = "./migen_src/normalize.py:26" *) 1'h1;
  assign \$37  = val_in == (* src = "./migen_src/normalize.py:29" *) 17'h1ffff;
  assign \$3  = val_in == (* src = "./migen_src/normalize.py:29" *) 17'h1ffff;
  assign \$39  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fffd;
  assign \$41  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff9;
  assign \$43  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff1;
  assign \$45  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffe1;
  assign \$47  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffc1;
  assign \$49  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff81;
  assign \$51  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff01;
  assign \$53  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fe01;
  assign \$55  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fc01;
  assign \$57  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f801;
  assign \$5  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fffd;
  assign \$59  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f001;
  assign \$61  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1e001;
  assign \$63  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1c001;
  assign \$65  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h18001;
  assign \$67  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h10001;
  assign \$70  = val_in + (* src = "./migen_src/normalize.py:32" *) 1'h1;
  assign \$73  = val_in + (* src = "./migen_src/normalize.py:40" *) 3'h4;
  assign \$75  = \$73  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$78  = val_in + (* src = "./migen_src/normalize.py:40" *) 4'h8;
  assign \$7  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff9;
  assign \$80  = \$78  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$83  = val_in + (* src = "./migen_src/normalize.py:40" *) 5'h10;
  assign \$85  = \$83  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$88  = val_in + (* src = "./migen_src/normalize.py:40" *) 6'h20;
  assign \$90  = \$88  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$93  = val_in + (* src = "./migen_src/normalize.py:40" *) 7'h40;
  assign \$95  = \$93  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$98  = val_in + (* src = "./migen_src/normalize.py:40" *) 8'h80;
  always @(posedge clk)
      val_out <= \$next\val_out ;
  always @(posedge clk)
      ssss <= \$next\ssss ;
  always @* begin
    \$next\ssss  = ssss;
    casez (valid)
      1'h1:
          casez (\$1 )
            1'h1:
                casez ({ \$33 , \$31 , \$29 , \$27 , \$25 , \$23 , \$21 , \$19 , \$17 , \$15 , \$13 , \$11 , \$9 , \$7 , \$5 , \$3  })
                  16'bzzzzzzzzzzzzzzz1:
                      \$next\ssss  = 5'h01;
                  16'bzzzzzzzzzzzzzz1z:
                      \$next\ssss  = 5'h02;
                  16'bzzzzzzzzzzzzz1zz:
                      \$next\ssss  = 5'h03;
                  16'bzzzzzzzzzzzz1zzz:
                      \$next\ssss  = 5'h04;
                  16'bzzzzzzzzzzz1zzzz:
                      \$next\ssss  = 5'h05;
                  16'bzzzzzzzzzz1zzzzz:
                      \$next\ssss  = 5'h06;
                  16'bzzzzzzzzz1zzzzzz:
                      \$next\ssss  = 5'h07;
                  16'bzzzzzzzz1zzzzzzz:
                      \$next\ssss  = 5'h08;
                  16'bzzzzzzz1zzzzzzzz:
                      \$next\ssss  = 5'h09;
                  16'bzzzzzz1zzzzzzzzz:
                      \$next\ssss  = 5'h0a;
                  16'bzzzzz1zzzzzzzzzz:
                      \$next\ssss  = 5'h0b;
                  16'bzzzz1zzzzzzzzzzz:
                      \$next\ssss  = 5'h0c;
                  16'bzzz1zzzzzzzzzzzz:
                      \$next\ssss  = 5'h0d;
                  16'bzz1zzzzzzzzzzzzz:
                      \$next\ssss  = 5'h0e;
                  16'bz1zzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h0f;
                  16'b1zzzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h10;
                endcase
            1'hz:
                casez ({ val_in[0], val_in[1], val_in[2], val_in[3], val_in[4], val_in[5], val_in[6], val_in[7], val_in[8], val_in[9], val_in[10], val_in[11], val_in[12], val_in[13], val_in[14], val_in[15] })
                  16'bzzzzzzzzzzzzzzz1:
                      \$next\ssss  = 5'h10;
                  16'bzzzzzzzzzzzzzz1z:
                      \$next\ssss  = 5'h0f;
                  16'bzzzzzzzzzzzzz1zz:
                      \$next\ssss  = 5'h0e;
                  16'bzzzzzzzzzzzz1zzz:
                      \$next\ssss  = 5'h0d;
                  16'bzzzzzzzzzzz1zzzz:
                      \$next\ssss  = 5'h0c;
                  16'bzzzzzzzzzz1zzzzz:
                      \$next\ssss  = 5'h0b;
                  16'bzzzzzzzzz1zzzzzz:
                      \$next\ssss  = 5'h0a;
                  16'bzzzzzzzz1zzzzzzz:
                      \$next\ssss  = 5'h09;
                  16'bzzzzzzz1zzzzzzzz:
                      \$next\ssss  = 5'h08;
                  16'bzzzzzz1zzzzzzzzz:
                      \$next\ssss  = 5'h07;
                  16'bzzzzz1zzzzzzzzzz:
                      \$next\ssss  = 5'h06;
                  16'bzzzz1zzzzzzzzzzz:
                      \$next\ssss  = 5'h05;
                  16'bzzz1zzzzzzzzzzzz:
                      \$next\ssss  = 5'h04;
                  16'bzz1zzzzzzzzzzzzz:
                      \$next\ssss  = 5'h03;
                  16'bz1zzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h02;
                  16'b1zzzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h01;
                  16'hzzzz:
                      \$next\ssss  = 5'h00;
                endcase
          endcase
    endcase
    casez (rst)
      1'h1:
          \$next\ssss  = 5'h00;
    endcase
  end
  always @* begin
    \$next\val_out  = val_out;
    casez (valid)
      1'h1:
          casez (\$35 )
            1'h1:
                casez ({ \$67 , \$65 , \$63 , \$61 , \$59 , \$57 , \$55 , \$53 , \$51 , \$49 , \$47 , \$45 , \$43 , \$41 , \$39 , \$37  })
                  16'bzzzzzzzzzzzzzzz1:
                      \$next\val_out  = \$69 [15:0];
                  16'bzzzzzzzzzzzzzz1z:
                      \$next\val_out  = \$72 [15:0];
                  16'bzzzzzzzzzzzzz1zz:
                      \$next\val_out  = \$77 [15:0];
                  16'bzzzzzzzzzzzz1zzz:
                      \$next\val_out  = \$82 [15:0];
                  16'bzzzzzzzzzzz1zzzz:
                      \$next\val_out  = \$87 [15:0];
                  16'bzzzzzzzzzz1zzzzz:
                      \$next\val_out  = \$92 [15:0];
                  16'bzzzzzzzzz1zzzzzz:
                      \$next\val_out  = \$97 [15:0];
                  16'bzzzzzzzz1zzzzzzz:
                      \$next\val_out  = \$102 [15:0];
                  16'bzzzzzzz1zzzzzzzz:
                      \$next\val_out  = \$107 [15:0];
                  16'bzzzzzz1zzzzzzzzz:
                      \$next\val_out  = \$112 [15:0];
                  16'bzzzzz1zzzzzzzzzz:
                      \$next\val_out  = \$117 [15:0];
                  16'bzzzz1zzzzzzzzzzz:
                      \$next\val_out  = \$122 [15:0];
                  16'bzzz1zzzzzzzzzzzz:
                      \$next\val_out  = \$127 [15:0];
                  16'bzz1zzzzzzzzzzzzz:
                      \$next\val_out  = \$132 [15:0];
                  16'bz1zzzzzzzzzzzzzz:
                      \$next\val_out  = \$137 [15:0];
                  16'b1zzzzzzzzzzzzzzz:
                      \$next\val_out  = \$142 [15:0];
                endcase
            1'hz:
                \$next\val_out  = val_in[15:0];
          endcase
    endcase
    casez (rst)
      1'h1:
          \$next\val_out  = 16'h0000;
    endcase
  end
  assign \$69  = \$70 ;
  assign \$72  = \$75 ;
  assign \$77  = \$80 ;
  assign \$82  = \$85 ;
  assign \$87  = \$90 ;
  assign \$92  = \$95 ;
  assign \$97  = \$100 ;
  assign \$102  = \$105 ;
  assign \$107  = \$110 ;
  assign \$112  = \$115 ;
  assign \$117  = \$120 ;
  assign \$122  = \$125 ;
  assign \$127  = \$130 ;
  assign \$132  = \$135 ;
  assign \$137  = \$140 ;
  assign \$142  = \$145 ;
endmodule

(* \nmigen.hierarchy  = "top.pixel4" *)
(* generator = "nMigen" *)
module pixel4(val_in, rst, clk, ssss, val_out, valid);
  wire \$1 ;
  wire [18:0] \$100 ;
  wire [18:0] \$102 ;
  wire [17:0] \$103 ;
  wire [18:0] \$105 ;
  wire [18:0] \$107 ;
  wire [17:0] \$108 ;
  wire \$11 ;
  wire [18:0] \$110 ;
  wire [18:0] \$112 ;
  wire [17:0] \$113 ;
  wire [18:0] \$115 ;
  wire [18:0] \$117 ;
  wire [17:0] \$118 ;
  wire [18:0] \$120 ;
  wire [18:0] \$122 ;
  wire [17:0] \$123 ;
  wire [18:0] \$125 ;
  wire [18:0] \$127 ;
  wire [17:0] \$128 ;
  wire \$13 ;
  wire [18:0] \$130 ;
  wire [18:0] \$132 ;
  wire [17:0] \$133 ;
  wire [18:0] \$135 ;
  wire [18:0] \$137 ;
  wire [17:0] \$138 ;
  wire [18:0] \$140 ;
  wire [18:0] \$142 ;
  wire [17:0] \$143 ;
  wire [18:0] \$145 ;
  wire \$15 ;
  wire \$17 ;
  wire \$19 ;
  wire \$21 ;
  wire \$23 ;
  wire \$25 ;
  wire \$27 ;
  wire \$29 ;
  wire \$3 ;
  wire \$31 ;
  wire \$33 ;
  wire \$35 ;
  wire \$37 ;
  wire \$39 ;
  wire \$41 ;
  wire \$43 ;
  wire \$45 ;
  wire \$47 ;
  wire \$49 ;
  wire \$5 ;
  wire \$51 ;
  wire \$53 ;
  wire \$55 ;
  wire \$57 ;
  wire \$59 ;
  wire \$61 ;
  wire \$63 ;
  wire \$65 ;
  wire \$67 ;
  wire [17:0] \$69 ;
  wire \$7 ;
  wire [17:0] \$70 ;
  wire [18:0] \$72 ;
  wire [17:0] \$73 ;
  wire [18:0] \$75 ;
  wire [18:0] \$77 ;
  wire [17:0] \$78 ;
  wire [18:0] \$80 ;
  wire [18:0] \$82 ;
  wire [17:0] \$83 ;
  wire [18:0] \$85 ;
  wire [18:0] \$87 ;
  wire [17:0] \$88 ;
  wire \$9 ;
  wire [18:0] \$90 ;
  wire [18:0] \$92 ;
  wire [17:0] \$93 ;
  wire [18:0] \$95 ;
  wire [18:0] \$97 ;
  wire [17:0] \$98 ;
  (* src = "./migen_src/normalize.py:13" *)
  reg [4:0] \$next\ssss ;
  (* src = "./migen_src/normalize.py:12" *)
  reg [15:0] \$next\val_out ;
  (* src = "/anaconda3/envs/py36/lib/python3.6/site-packages/nmigen/hdl/ir.py:329" *)
  input clk;
  (* src = "/anaconda3/envs/py36/lib/python3.6/site-packages/nmigen/hdl/ir.py:329" *)
  input rst;
  (* init = 5'h00 *)
  (* src = "./migen_src/normalize.py:13" *)
  output [4:0] ssss;
  reg [4:0] ssss = 5'h00;
  (* src = "./migen_src/normalize.py:11" *)
  input [16:0] val_in;
  (* init = 16'h0000 *)
  (* src = "./migen_src/normalize.py:12" *)
  output [15:0] val_out;
  reg [15:0] val_out = 16'h0000;
  (* src = "./migen_src/normalize.py:14" *)
  input valid;
  assign \$9  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff1;
  assign \$100  = \$98  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$103  = val_in + (* src = "./migen_src/normalize.py:40" *) 9'h100;
  assign \$105  = \$103  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$108  = val_in + (* src = "./migen_src/normalize.py:40" *) 10'h200;
  assign \$110  = \$108  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$113  = val_in + (* src = "./migen_src/normalize.py:40" *) 11'h400;
  assign \$115  = \$113  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$118  = val_in + (* src = "./migen_src/normalize.py:40" *) 12'h800;
  assign \$11  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffe1;
  assign \$120  = \$118  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$123  = val_in + (* src = "./migen_src/normalize.py:40" *) 13'h1000;
  assign \$125  = \$123  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$128  = val_in + (* src = "./migen_src/normalize.py:40" *) 14'h2000;
  assign \$130  = \$128  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$133  = val_in + (* src = "./migen_src/normalize.py:40" *) 15'h4000;
  assign \$135  = \$133  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$138  = val_in + (* src = "./migen_src/normalize.py:40" *) 16'h8000;
  assign \$13  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffc1;
  assign \$140  = \$138  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$143  = val_in + (* src = "./migen_src/normalize.py:40" *) 17'h10000;
  assign \$145  = \$143  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$15  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff81;
  assign \$17  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff01;
  assign \$1  = val_in[16] == (* src = "./migen_src/normalize.py:26" *) 1'h1;
  assign \$19  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fe01;
  assign \$21  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fc01;
  assign \$23  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f801;
  assign \$25  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f001;
  assign \$27  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1e001;
  assign \$29  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1c001;
  assign \$31  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h18001;
  assign \$33  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h10001;
  assign \$35  = val_in[16] == (* src = "./migen_src/normalize.py:26" *) 1'h1;
  assign \$37  = val_in == (* src = "./migen_src/normalize.py:29" *) 17'h1ffff;
  assign \$3  = val_in == (* src = "./migen_src/normalize.py:29" *) 17'h1ffff;
  assign \$39  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fffd;
  assign \$41  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff9;
  assign \$43  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff1;
  assign \$45  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffe1;
  assign \$47  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ffc1;
  assign \$49  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff81;
  assign \$51  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1ff01;
  assign \$53  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fe01;
  assign \$55  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fc01;
  assign \$57  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f801;
  assign \$5  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fffd;
  assign \$59  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1f001;
  assign \$61  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1e001;
  assign \$63  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1c001;
  assign \$65  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h18001;
  assign \$67  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h10001;
  assign \$70  = val_in + (* src = "./migen_src/normalize.py:32" *) 1'h1;
  assign \$73  = val_in + (* src = "./migen_src/normalize.py:40" *) 3'h4;
  assign \$75  = \$73  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$78  = val_in + (* src = "./migen_src/normalize.py:40" *) 4'h8;
  assign \$7  = val_in >= (* src = "./migen_src/normalize.py:36" *) 17'h1fff9;
  assign \$80  = \$78  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$83  = val_in + (* src = "./migen_src/normalize.py:40" *) 5'h10;
  assign \$85  = \$83  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$88  = val_in + (* src = "./migen_src/normalize.py:40" *) 6'h20;
  assign \$90  = \$88  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$93  = val_in + (* src = "./migen_src/normalize.py:40" *) 7'h40;
  assign \$95  = \$93  - (* src = "./migen_src/normalize.py:40" *) 1'h1;
  assign \$98  = val_in + (* src = "./migen_src/normalize.py:40" *) 8'h80;
  always @(posedge clk)
      val_out <= \$next\val_out ;
  always @(posedge clk)
      ssss <= \$next\ssss ;
  always @* begin
    \$next\ssss  = ssss;
    casez (valid)
      1'h1:
          casez (\$1 )
            1'h1:
                casez ({ \$33 , \$31 , \$29 , \$27 , \$25 , \$23 , \$21 , \$19 , \$17 , \$15 , \$13 , \$11 , \$9 , \$7 , \$5 , \$3  })
                  16'bzzzzzzzzzzzzzzz1:
                      \$next\ssss  = 5'h01;
                  16'bzzzzzzzzzzzzzz1z:
                      \$next\ssss  = 5'h02;
                  16'bzzzzzzzzzzzzz1zz:
                      \$next\ssss  = 5'h03;
                  16'bzzzzzzzzzzzz1zzz:
                      \$next\ssss  = 5'h04;
                  16'bzzzzzzzzzzz1zzzz:
                      \$next\ssss  = 5'h05;
                  16'bzzzzzzzzzz1zzzzz:
                      \$next\ssss  = 5'h06;
                  16'bzzzzzzzzz1zzzzzz:
                      \$next\ssss  = 5'h07;
                  16'bzzzzzzzz1zzzzzzz:
                      \$next\ssss  = 5'h08;
                  16'bzzzzzzz1zzzzzzzz:
                      \$next\ssss  = 5'h09;
                  16'bzzzzzz1zzzzzzzzz:
                      \$next\ssss  = 5'h0a;
                  16'bzzzzz1zzzzzzzzzz:
                      \$next\ssss  = 5'h0b;
                  16'bzzzz1zzzzzzzzzzz:
                      \$next\ssss  = 5'h0c;
                  16'bzzz1zzzzzzzzzzzz:
                      \$next\ssss  = 5'h0d;
                  16'bzz1zzzzzzzzzzzzz:
                      \$next\ssss  = 5'h0e;
                  16'bz1zzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h0f;
                  16'b1zzzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h10;
                endcase
            1'hz:
                casez ({ val_in[0], val_in[1], val_in[2], val_in[3], val_in[4], val_in[5], val_in[6], val_in[7], val_in[8], val_in[9], val_in[10], val_in[11], val_in[12], val_in[13], val_in[14], val_in[15] })
                  16'bzzzzzzzzzzzzzzz1:
                      \$next\ssss  = 5'h10;
                  16'bzzzzzzzzzzzzzz1z:
                      \$next\ssss  = 5'h0f;
                  16'bzzzzzzzzzzzzz1zz:
                      \$next\ssss  = 5'h0e;
                  16'bzzzzzzzzzzzz1zzz:
                      \$next\ssss  = 5'h0d;
                  16'bzzzzzzzzzzz1zzzz:
                      \$next\ssss  = 5'h0c;
                  16'bzzzzzzzzzz1zzzzz:
                      \$next\ssss  = 5'h0b;
                  16'bzzzzzzzzz1zzzzzz:
                      \$next\ssss  = 5'h0a;
                  16'bzzzzzzzz1zzzzzzz:
                      \$next\ssss  = 5'h09;
                  16'bzzzzzzz1zzzzzzzz:
                      \$next\ssss  = 5'h08;
                  16'bzzzzzz1zzzzzzzzz:
                      \$next\ssss  = 5'h07;
                  16'bzzzzz1zzzzzzzzzz:
                      \$next\ssss  = 5'h06;
                  16'bzzzz1zzzzzzzzzzz:
                      \$next\ssss  = 5'h05;
                  16'bzzz1zzzzzzzzzzzz:
                      \$next\ssss  = 5'h04;
                  16'bzz1zzzzzzzzzzzzz:
                      \$next\ssss  = 5'h03;
                  16'bz1zzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h02;
                  16'b1zzzzzzzzzzzzzzz:
                      \$next\ssss  = 5'h01;
                  16'hzzzz:
                      \$next\ssss  = 5'h00;
                endcase
          endcase
    endcase
    casez (rst)
      1'h1:
          \$next\ssss  = 5'h00;
    endcase
  end
  always @* begin
    \$next\val_out  = val_out;
    casez (valid)
      1'h1:
          casez (\$35 )
            1'h1:
                casez ({ \$67 , \$65 , \$63 , \$61 , \$59 , \$57 , \$55 , \$53 , \$51 , \$49 , \$47 , \$45 , \$43 , \$41 , \$39 , \$37  })
                  16'bzzzzzzzzzzzzzzz1:
                      \$next\val_out  = \$69 [15:0];
                  16'bzzzzzzzzzzzzzz1z:
                      \$next\val_out  = \$72 [15:0];
                  16'bzzzzzzzzzzzzz1zz:
                      \$next\val_out  = \$77 [15:0];
                  16'bzzzzzzzzzzzz1zzz:
                      \$next\val_out  = \$82 [15:0];
                  16'bzzzzzzzzzzz1zzzz:
                      \$next\val_out  = \$87 [15:0];
                  16'bzzzzzzzzzz1zzzzz:
                      \$next\val_out  = \$92 [15:0];
                  16'bzzzzzzzzz1zzzzzz:
                      \$next\val_out  = \$97 [15:0];
                  16'bzzzzzzzz1zzzzzzz:
                      \$next\val_out  = \$102 [15:0];
                  16'bzzzzzzz1zzzzzzzz:
                      \$next\val_out  = \$107 [15:0];
                  16'bzzzzzz1zzzzzzzzz:
                      \$next\val_out  = \$112 [15:0];
                  16'bzzzzz1zzzzzzzzzz:
                      \$next\val_out  = \$117 [15:0];
                  16'bzzzz1zzzzzzzzzzz:
                      \$next\val_out  = \$122 [15:0];
                  16'bzzz1zzzzzzzzzzzz:
                      \$next\val_out  = \$127 [15:0];
                  16'bzz1zzzzzzzzzzzzz:
                      \$next\val_out  = \$132 [15:0];
                  16'bz1zzzzzzzzzzzzzz:
                      \$next\val_out  = \$137 [15:0];
                  16'b1zzzzzzzzzzzzzzz:
                      \$next\val_out  = \$142 [15:0];
                endcase
            1'hz:
                \$next\val_out  = val_in[15:0];
          endcase
    endcase
    casez (rst)
      1'h1:
          \$next\val_out  = 16'h0000;
    endcase
  end
  assign \$69  = \$70 ;
  assign \$72  = \$75 ;
  assign \$77  = \$80 ;
  assign \$82  = \$85 ;
  assign \$87  = \$90 ;
  assign \$92  = \$95 ;
  assign \$97  = \$100 ;
  assign \$102  = \$105 ;
  assign \$107  = \$110 ;
  assign \$112  = \$115 ;
  assign \$117  = \$120 ;
  assign \$122  = \$125 ;
  assign \$127  = \$130 ;
  assign \$132  = \$135 ;
  assign \$137  = \$140 ;
  assign \$142  = \$145 ;
endmodule

(* \nmigen.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "nMigen" *)
module top(valid_in, val_in2, val_in3, val_in4, rst, clk, val_out1, val_out2, val_out3, val_out4, ssss1, ssss2, ssss3, ssss4, valid_out, val_in1);
  (* src = "./migen_src/normalize.py:11" *)
  reg [16:0] \$next\pixel1_val_in ;
  (* src = "./migen_src/normalize.py:14" *)
  reg \$next\pixel1_valid ;
  (* src = "./migen_src/normalize.py:11" *)
  reg [16:0] \$next\pixel2_val_in ;
  (* src = "./migen_src/normalize.py:14" *)
  reg \$next\pixel2_valid ;
  (* src = "./migen_src/normalize.py:11" *)
  reg [16:0] \$next\pixel3_val_in ;
  (* src = "./migen_src/normalize.py:14" *)
  reg \$next\pixel3_valid ;
  (* src = "./migen_src/normalize.py:11" *)
  reg [16:0] \$next\pixel4_val_in ;
  (* src = "./migen_src/normalize.py:14" *)
  reg \$next\pixel4_valid ;
  (* src = "./migen_src/normalize.py:79" *)
  reg [4:0] \$next\ssss1 ;
  (* src = "./migen_src/normalize.py:80" *)
  reg [4:0] \$next\ssss2 ;
  (* src = "./migen_src/normalize.py:81" *)
  reg [4:0] \$next\ssss3 ;
  (* src = "./migen_src/normalize.py:82" *)
  reg [4:0] \$next\ssss4 ;
  (* src = "./migen_src/normalize.py:74" *)
  reg [15:0] \$next\val_out1 ;
  (* src = "./migen_src/normalize.py:75" *)
  reg [15:0] \$next\val_out2 ;
  (* src = "./migen_src/normalize.py:76" *)
  reg [15:0] \$next\val_out3 ;
  (* src = "./migen_src/normalize.py:77" *)
  reg [15:0] \$next\val_out4 ;
  (* src = "./migen_src/normalize.py:85" *)
  reg \$next\valid_out ;
  (* src = "/anaconda3/envs/py36/lib/python3.6/site-packages/nmigen/hdl/ir.py:329" *)
  input clk;
  (* src = "./migen_src/normalize.py:13" *)
  wire [4:0] pixel1_ssss;
  (* src = "./migen_src/normalize.py:11" *)
  wire [16:0] pixel1_val_in;
  (* src = "./migen_src/normalize.py:12" *)
  wire [15:0] pixel1_val_out;
  (* src = "./migen_src/normalize.py:14" *)
  wire pixel1_valid;
  (* src = "./migen_src/normalize.py:13" *)
  wire [4:0] pixel2_ssss;
  (* src = "./migen_src/normalize.py:11" *)
  wire [16:0] pixel2_val_in;
  (* src = "./migen_src/normalize.py:12" *)
  wire [15:0] pixel2_val_out;
  (* src = "./migen_src/normalize.py:14" *)
  wire pixel2_valid;
  (* src = "./migen_src/normalize.py:13" *)
  wire [4:0] pixel3_ssss;
  (* src = "./migen_src/normalize.py:11" *)
  wire [16:0] pixel3_val_in;
  (* src = "./migen_src/normalize.py:12" *)
  wire [15:0] pixel3_val_out;
  (* src = "./migen_src/normalize.py:14" *)
  wire pixel3_valid;
  (* src = "./migen_src/normalize.py:13" *)
  wire [4:0] pixel4_ssss;
  (* src = "./migen_src/normalize.py:11" *)
  wire [16:0] pixel4_val_in;
  (* src = "./migen_src/normalize.py:12" *)
  wire [15:0] pixel4_val_out;
  (* src = "./migen_src/normalize.py:14" *)
  wire pixel4_valid;
  (* src = "/anaconda3/envs/py36/lib/python3.6/site-packages/nmigen/hdl/ir.py:329" *)
  input rst;
  (* src = "./migen_src/normalize.py:79" *)
  output [4:0] ssss1;
  (* src = "./migen_src/normalize.py:80" *)
  output [4:0] ssss2;
  (* src = "./migen_src/normalize.py:81" *)
  output [4:0] ssss3;
  (* src = "./migen_src/normalize.py:82" *)
  output [4:0] ssss4;
  (* src = "./migen_src/normalize.py:69" *)
  input [16:0] val_in1;
  (* src = "./migen_src/normalize.py:70" *)
  input [16:0] val_in2;
  (* src = "./migen_src/normalize.py:71" *)
  input [16:0] val_in3;
  (* src = "./migen_src/normalize.py:72" *)
  input [16:0] val_in4;
  (* src = "./migen_src/normalize.py:74" *)
  output [15:0] val_out1;
  (* src = "./migen_src/normalize.py:75" *)
  output [15:0] val_out2;
  (* src = "./migen_src/normalize.py:76" *)
  output [15:0] val_out3;
  (* src = "./migen_src/normalize.py:77" *)
  output [15:0] val_out4;
  (* src = "./migen_src/normalize.py:84" *)
  input valid_in;
  (* init = 1'h0 *)
  (* src = "./migen_src/normalize.py:85" *)
  output valid_out;
  reg valid_out = 1'h0;
  always @(posedge clk)
      valid_out <= \$next\valid_out ;
  pixel1 pixel1 (
    .clk(clk),
    .rst(rst),
    .ssss(pixel1_ssss),
    .val_in(pixel1_val_in),
    .val_out(pixel1_val_out),
    .valid(pixel1_valid)
  );
  pixel2 pixel2 (
    .clk(clk),
    .rst(rst),
    .ssss(pixel2_ssss),
    .val_in(pixel2_val_in),
    .val_out(pixel2_val_out),
    .valid(pixel2_valid)
  );
  pixel3 pixel3 (
    .clk(clk),
    .rst(rst),
    .ssss(pixel3_ssss),
    .val_in(pixel3_val_in),
    .val_out(pixel3_val_out),
    .valid(pixel3_valid)
  );
  pixel4 pixel4 (
    .clk(clk),
    .rst(rst),
    .ssss(pixel4_ssss),
    .val_in(pixel4_val_in),
    .val_out(pixel4_val_out),
    .valid(pixel4_valid)
  );
  always @* begin
    \$next\pixel1_val_in  = 17'h00000;
    \$next\pixel1_val_in  = val_in1;
  end
  always @* begin
    \$next\pixel1_valid  = 1'h0;
    \$next\pixel1_valid  = valid_in;
  end
  always @* begin
    \$next\ssss3  = 5'h00;
    \$next\ssss3  = pixel3_ssss;
  end
  always @* begin
    \$next\val_out3  = 16'h0000;
    \$next\val_out3  = pixel3_val_out;
  end
  always @* begin
    \$next\pixel4_val_in  = 17'h00000;
    \$next\pixel4_val_in  = val_in4;
  end
  always @* begin
    \$next\pixel4_valid  = 1'h0;
    \$next\pixel4_valid  = valid_in;
  end
  always @* begin
    \$next\ssss4  = 5'h00;
    \$next\ssss4  = pixel4_ssss;
  end
  always @* begin
    \$next\val_out4  = 16'h0000;
    \$next\val_out4  = pixel4_val_out;
  end
  always @* begin
    \$next\valid_out  = valid_out;
    \$next\valid_out  = valid_in;
    casez (rst)
      1'h1:
          \$next\valid_out  = 1'h0;
    endcase
  end
  always @* begin
    \$next\ssss1  = 5'h00;
    \$next\ssss1  = pixel1_ssss;
  end
  always @* begin
    \$next\val_out1  = 16'h0000;
    \$next\val_out1  = pixel1_val_out;
  end
  always @* begin
    \$next\pixel2_val_in  = 17'h00000;
    \$next\pixel2_val_in  = val_in2;
  end
  always @* begin
    \$next\pixel2_valid  = 1'h0;
    \$next\pixel2_valid  = valid_in;
  end
  always @* begin
    \$next\ssss2  = 5'h00;
    \$next\ssss2  = pixel2_ssss;
  end
  always @* begin
    \$next\val_out2  = 16'h0000;
    \$next\val_out2  = pixel2_val_out;
  end
  always @* begin
    \$next\pixel3_val_in  = 17'h00000;
    \$next\pixel3_val_in  = val_in3;
  end
  always @* begin
    \$next\pixel3_valid  = 1'h0;
    \$next\pixel3_valid  = valid_in;
  end
  assign val_out4 = \$next\val_out4 ;
  assign ssss4 = \$next\ssss4 ;
  assign pixel4_valid = \$next\pixel4_valid ;
  assign pixel4_val_in = \$next\pixel4_val_in ;
  assign val_out3 = \$next\val_out3 ;
  assign ssss3 = \$next\ssss3 ;
  assign pixel3_valid = \$next\pixel3_valid ;
  assign pixel3_val_in = \$next\pixel3_val_in ;
  assign val_out2 = \$next\val_out2 ;
  assign ssss2 = \$next\ssss2 ;
  assign pixel2_valid = \$next\pixel2_valid ;
  assign pixel2_val_in = \$next\pixel2_val_in ;
  assign val_out1 = \$next\val_out1 ;
  assign ssss1 = \$next\ssss1 ;
  assign pixel1_valid = \$next\pixel1_valid ;
  assign pixel1_val_in = \$next\pixel1_val_in ;
endmodule

