/* Generated by Yosys 0.8+     369 (git sha1 ea0e0722, clang 10.0.1 -fPIC -Os) */

(* \nmigen.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "nMigen" *)
module top(enc_left_ctr, valid_left, rst, clk, enc_right, enc_right_ctr, valid_right, enc_left);
  (* src = "./migen_src/pipeline_reg.py:28" *)
  reg [61:0] \$next\enc_right ;
  (* src = "./migen_src/pipeline_reg.py:29" *)
  reg [5:0] \$next\enc_right_ctr ;
  (* src = "./migen_src/pipeline_reg.py:32" *)
  reg \$next\valid_right ;
  (* src = "/anaconda3/envs/py36/lib/python3.6/site-packages/nmigen/hdl/ir.py:329" *)
  input clk;
  (* src = "./migen_src/pipeline_reg.py:24" *)
  input [61:0] enc_left;
  (* src = "./migen_src/pipeline_reg.py:25" *)
  input [5:0] enc_left_ctr;
  (* init = 62'h0000000000000000 *)
  (* src = "./migen_src/pipeline_reg.py:28" *)
  output [61:0] enc_right;
  reg [61:0] enc_right = 62'h0000000000000000;
  (* init = 6'h00 *)
  (* src = "./migen_src/pipeline_reg.py:29" *)
  output [5:0] enc_right_ctr;
  reg [5:0] enc_right_ctr = 6'h00;
  (* src = "/anaconda3/envs/py36/lib/python3.6/site-packages/nmigen/hdl/ir.py:329" *)
  input rst;
  (* src = "./migen_src/pipeline_reg.py:31" *)
  input valid_left;
  (* init = 1'h0 *)
  (* src = "./migen_src/pipeline_reg.py:32" *)
  output valid_right;
  reg valid_right = 1'h0;
  always @(posedge clk)
      valid_right <= \$next\valid_right ;
  always @(posedge clk)
      enc_right_ctr <= \$next\enc_right_ctr ;
  always @(posedge clk)
      enc_right <= \$next\enc_right ;
  always @* begin
    \$next\enc_right  = enc_right;
    \$next\enc_right  = enc_left;
    casez (rst)
      1'h1:
          \$next\enc_right  = 62'h0000000000000000;
    endcase
  end
  always @* begin
    \$next\enc_right_ctr  = enc_right_ctr;
    \$next\enc_right_ctr  = enc_left_ctr;
    casez (rst)
      1'h1:
          \$next\enc_right_ctr  = 6'h00;
    endcase
  end
  always @* begin
    \$next\valid_right  = valid_right;
    \$next\valid_right  = valid_left;
    casez (rst)
      1'h1:
          \$next\valid_right  = 1'h0;
    endcase
  end
endmodule

