/* Generated by Yosys 0.8+     369 (git sha1 ea0e0722, clang 10.0.1 -fPIC -Os) */

(* \nmigen.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "nMigen" *)
module top(clk, height, width, rst);
  (* src = "./migen_src/register_file.py:11" *)
  reg [15:0] \$next\height ;
  (* src = "./migen_src/register_file.py:22" *)
  reg [15:0] \$next\height_reg ;
  (* src = "./migen_src/register_file.py:12" *)
  reg [15:0] \$next\width ;
  (* src = "./migen_src/register_file.py:21" *)
  reg [15:0] \$next\width_reg ;
  (* src = "/anaconda3/envs/py36/lib/python3.6/site-packages/nmigen/hdl/ir.py:329" *)
  input clk;
  (* src = "./migen_src/register_file.py:11" *)
  output [15:0] height;
  (* init = 16'h0000 *)
  (* src = "./migen_src/register_file.py:22" *)
  reg [15:0] height_reg = 16'h0000;
  (* src = "/anaconda3/envs/py36/lib/python3.6/site-packages/nmigen/hdl/ir.py:329" *)
  input rst;
  (* src = "./migen_src/register_file.py:12" *)
  output [15:0] width;
  (* init = 16'h0000 *)
  (* src = "./migen_src/register_file.py:21" *)
  reg [15:0] width_reg = 16'h0000;
  always @(posedge clk)
      height_reg <= \$next\height_reg ;
  always @(posedge clk)
      width_reg <= \$next\width_reg ;
  always @* begin
    \$next\width_reg  = width_reg;
    \$next\width_reg  = 16'h1000;
    casez (rst)
      1'h1:
          \$next\width_reg  = 16'h0000;
    endcase
  end
  always @* begin
    \$next\height_reg  = height_reg;
    \$next\height_reg  = 16'h0c00;
    casez (rst)
      1'h1:
          \$next\height_reg  = 16'h0000;
    endcase
  end
  always @* begin
    \$next\width  = 16'h0000;
    \$next\width  = width_reg;
  end
  always @* begin
    \$next\height  = 16'h0000;
    \$next\height  = height_reg;
  end
  assign height = \$next\height ;
  assign width = \$next\width ;
endmodule

