/* Generated by Yosys 0.8+     369 (git sha1 ea0e0722, clang 10.0.1 -fPIC -Os) */

(* \nmigen.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "nMigen" *)
module top(data_out, data_in);
  (* src = "reverser.py:40" *)
  reg [31:0] \$next\data_out ;
  (* src = "reverser.py:39" *)
  input [31:0] data_in;
  (* src = "reverser.py:40" *)
  output [31:0] data_out;
  always @* begin
    \$next\data_out  = 32'd0;
    \$next\data_out [31] = data_in[0];
    \$next\data_out [30] = data_in[1];
    \$next\data_out [29] = data_in[2];
    \$next\data_out [28] = data_in[3];
    \$next\data_out [27] = data_in[4];
    \$next\data_out [26] = data_in[5];
    \$next\data_out [25] = data_in[6];
    \$next\data_out [24] = data_in[7];
    \$next\data_out [23] = data_in[8];
    \$next\data_out [22] = data_in[9];
    \$next\data_out [21] = data_in[10];
    \$next\data_out [20] = data_in[11];
    \$next\data_out [19] = data_in[12];
    \$next\data_out [18] = data_in[13];
    \$next\data_out [17] = data_in[14];
    \$next\data_out [16] = data_in[15];
    \$next\data_out [15] = data_in[16];
    \$next\data_out [14] = data_in[17];
    \$next\data_out [13] = data_in[18];
    \$next\data_out [12] = data_in[19];
    \$next\data_out [11] = data_in[20];
    \$next\data_out [10] = data_in[21];
    \$next\data_out [9] = data_in[22];
    \$next\data_out [8] = data_in[23];
    \$next\data_out [7] = data_in[24];
    \$next\data_out [6] = data_in[25];
    \$next\data_out [5] = data_in[26];
    \$next\data_out [4] = data_in[27];
    \$next\data_out [3] = data_in[28];
    \$next\data_out [2] = data_in[29];
    \$next\data_out [1] = data_in[30];
    \$next\data_out [0] = data_in[31];
  end
  assign data_out = \$next\data_out ;
endmodule

